### ISSUE TITLE
Specify game modes for screenshots

### ISSUE THREAD

**Issue by culinko** [andburn/hdt-plugin-endgame#1]
Hello! It would be amazing if you could specify game modes for the screenshot function, so the user could toggle in which modes he wants the screenshots to be taken (e.g. ranked, arena, friendly, etc.). Thanks!

**Comment by andburn** [comment]
This does make sense. It might be a bit tricky because of the note dialog thing, but leave it with me.

**Comment by andburn** [comment]
Also in latest update - hopefully!
