### ISSUE TITLE
Not working in HDT latest version

### ISSUE THREAD

**Issue by DarkCr0w** [andburn/hdt-plugin-endgame#11]
Since I and 2 of my friends updated to the last HDT version, the pop up window to select the meta deck and add a note doesnt appear anymore.

The importing meta-decks still working tho.

Hope you can solve it. Keep up the good job :D :dancer: 

Ps: Yes, we all tried to unistall all the stuff and tried it again but it still not working.

**Comment by andburn** [comment]
Thanks for the report, will look into it in the next couple of days.

**Comment by andburn** [comment]
OK fixed now, see the [latest release](https://github.com/andburn/hdt-plugin-endgame/releases/latest).
