### ISSUE TITLE
Latest TempoStorm Import is Wild only

### ISSUE THREAD

**Issue by samcsilvr** [andburn/hdt-plugin-endgame#12]
With the most recent TempoStorm meta snapshot for Wild, I've lost previous Standard archetypes ("Delete previously imported decks" was enabled). Will this be an issue with that option going forward?

**Comment by andburn** [comment]
I'll have to look into it a bit, but I should be able to make it import both the snapshots and/or add options for it.

**Comment by andburn** [comment]
Fixed this for now, downloads standard only. Sorry about the delay.
