### ISSUE TITLE
Would like the Meta Snapshot for Wild mode as well

### ISSUE THREAD

**Issue by gaarden2000** [andburn/hdt-plugin-endgame#13]
I have used this plugin for a while now, and thoroughly enjoy it. Though as i started playing more wild, i realized none of the archetypes present in the meta snapshot you use are wild decks (understandable, since you're using the standard snapshot). I would greatly enjoy if you added an option for wild snapshot adding as well. 

Love your plugin, keep up the good work

**Comment by andburn** [comment]
Sorry about delay in replying. Will add this in next day or two.

**Comment by andburn** [comment]
Added this at last 🐌
