### ISSUE TITLE
Stats screens

### ISSUE THREAD

**Issue by TristanCP** [andburn/hdt-plugin-endgame#14]
Really nice plugin but what about the stats screen ?

Here is what would be nice, starting with your plugin : 

 On the stat screen, you could click on any matchup to see the decomposition. For example you are on your "Freeze Mage" deck stats, you click on the druid matchup which is 5-5, and you see this :
Anaconda druid : 2-0
Aggro druid : 3-0
Jade druid : 0-5

Would it be hard to do ? Maybe I could help.

**Comment by andburn** [comment]
Not really possible to add it to the main stats screen.
I've wanted to do something like this, though. Something simple in a separate window, should be doable. Leave it with me 🤔

**Comment by TristanCP** [comment]
Ok, nice. One more point : when I saide "really nice plugin", it was about the general concept, but after trying it : 
* I can't find where everything is written (the directory I've chosen stays empty).
* It does not memorize the deck types I add (For example, if I type "Anaconda druid", I want to this next time in the choices, not just "control", so it can aggregate in stats around the same label).

**Comment by andburn** [comment]
- it doesn't really create any additional files, it stores the deck type as part of the game note
- and it gets the deck types from the Tempostorm snapshot, to add your own you need to add a deck with the expected cards and tag it as 'Archetype'

I've changed things with this plugin, make it a bit less confusing. See the [README](../blob/master/README.md) for more info. Also, added some very basic stats.
