### ISSUE TITLE
cant import decks in lastest HDT

### ISSUE THREAD

**Issue by sdbds** [andburn/hdt-plugin-endgame#15]

**Comment by andburn** [comment]
So, you press the 'Import Meta Decks' button and nothing happens?

Seems to be working for me.

If its still happening, attach the HDT log file after you have tried.
[Find the log file here](https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues#hdt-log-files)

**Comment by sdbds** [comment]
sorry, i forgot updated to 0.4.3.now it worked.

**Comment by andburn** [comment]
👍
