### ISSUE TITLE
Crashes Whenever I try to view the stats

### ISSUE THREAD

**Issue by TheStormHerald** [andburn/hdt-plugin-endgame#18]
End game note option seems to work fine, but whenever I try to look at the stats my Deck Tracker crashes.

I have deleted the .dll and downloaded the most current version but I still have the issue.

Let me know if you need any additional information.

**Comment by andburn** [comment]
Seems ok for me.
If you can do the following, I might be able to see whats going wrong.

1. go to HDT `options > settings` and press the `open appdata folder` button
2. in the  window that opens, look for the file named `EndGame.ini` (if its not there change any of the plugins settings and it should appear)
3. open the file in *Notepad* or similar and add the following lines, and save
```
DeveloperMode = True
DebugLog = True
```
4. close and restart HDT
5. reproduce the crashing behaviour
6. close HDT
7. look for a file named `EndGame.log` in the same folder as the `EndGame.ini` from above, and attach it to this thread (drag'n'drop into a message)
8. also attach the HDT log file `hdt_log.txt`, find that in the `Log` folder within the folder from above
9. then go back and remove the two lines you added to `EndGame.ini` before starting HDT again

**Comment by TheStormHerald** [comment]
Sorry for the delay.

Here are the files

[EndGame.log](https://github.com/andburn/hdt-plugin-endgame/files/1467573/EndGame.log)
[hdt_log.txt](https://github.com/andburn/hdt-plugin-endgame/files/1467574/hdt_log.txt)

Let me know if you need anything else.

**Comment by TheStormHerald** [comment]
This may be duplicate information but here is the stack trace created when HDT crashes.
[stack trace.txt](https://github.com/andburn/hdt-plugin-endgame/files/1467632/stack.trace.txt)

**Comment by TheStormHerald** [comment]
I couldn't add the xml files directly so I zipped them together for you.  Let me know if you need anything else to help out.

Sorry to burden you with this.  

[HearthstoneDeckTracker.zip](https://github.com/andburn/hdt-plugin-endgame/files/1467723/HearthstoneDeckTracker.zip)

**Comment by andburn** [comment]
Try this version, I think it should be fixed.
[hdt-plugin-endgame.zip](https://github.com/andburn/hdt-plugin-endgame/files/1471896/hdt-plugin-endgame.zip)

**Comment by TheStormHerald** [comment]
So far it seems to work.  I will try a couple games real fast and let you know if it continues to work.  Thanks!

**Comment by TheStormHerald** [comment]
The stats seem to work now.  I am noticing a little lag when the post game note pops up that wasnt there before, but nothing more than a second or two.

Thanks for the fix.

**Comment by andburn** [comment]
Not sure about the lag, the change shouldn't really have any impact like that.

Did you remove the lines from the `EndGame.ini` file mentioned above? Leaving them in does cause lag.

**Comment by TheStormHerald** [comment]
I had my CAD program, rendering some stuff in the background.  That was causing the lag.  I went to post that it was working fine, but got distracted.

I did remove those lines, BTW.

Everything is working perfectly now.

-Cheers

**Comment by andburn** [comment]
Great 👌
