### ISSUE TITLE
Menu icons not showing in main plugin window

### ISSUE THREAD

**Issue by andburn** [andburn/hdt-plugin-endgame#20]
![zh1j1aa](https://user-images.githubusercontent.com/5419653/37547331-f93e1988-2968-11e8-9e4a-e3188dd565e4.jpg)

**Comment by ceceita** [comment]
im the one who reported , i thinked about it , i want to add somethings .. that may affect it
- im using the portable version not the one with installer
- plugin downloaded was a single.dll  i not updated it from the old plugin
- os is windows 8.1
- i installed the plugin in C:\Users\xx\AppData\Roaming\HearthstoneDeckTracker\Plugins  but i noticed that when i launch HDT , the Endgame.dll is also created in C:\Program Files (x86)\Hearthstone Deck Tracker\Plugins , even if i delete he comes back on hdt startup

**Comment by andburn** [comment]
@ceceita try the [latest version](https://github.com/andburn/hdt-plugin-endgame/releases/latest) both issues should be fixed

**Comment by ceceita** [comment]
this is fixed
