### ISSUE TITLE
Does not work at legend ranks

### ISSUE THREAD

**Issue by andburn** [andburn/hdt-plugin-endgame#21]
**Plugin log**
```
20180316 21:30:11 [DEBUG] Tracker: Mode Ranked 
20180316 21:30:11 [DEBUG] Settings: Get [RecordRankedArchetypes] 
20180316 21:30:11 [DEBUG] Tracker: Using default rank 25 
20180316 21:30:11 [DEBUG] Settings: Get [StartRank] 
20180316 21:30:11 [DEBUG] EndGame: Aborting main view navigation on 'note'
```

**Comment by ceceita** [comment]
A workaround  when in legend is to put Start Rank to 25 in the settings ..

**Comment by ceceita** [comment]
fixed , tested on 3 games
`20180320 20:39:11 [DEBUG]	Settings: Set Global[StartRank]=5`
`20180320 20:47:00 [DEBUG]	Tracker: Legend Rank found 10425`
`20180320 21:02:14 [DEBUG]	Tracker: Legend Rank found 9798`
`20180320 21:10:16 [DEBUG]	Tracker: Legend Rank found 10397`

screenshoot of ranks in stats and the icons visible ..

![](https://i.gyazo.com/a07464de0164e9ff5b869d8ad5440b3f.png)
