### ISSUE TITLE
Negative Seconds

### ISSUE THREAD

**Issue by therglerf** [andburn/hdt-plugin-endgame#9]
Is it possible to add negative seconds so like take the screen shot before the games over. I just had a game where i had perfect lethal and just hit them with a BM well played and would like to be able to relive that moment on my journey up the ranks.

**Comment by andburn** [comment]
Unfortunately not really possible. It would need to take screen shots all the time and work backwards when the game is over, this would likely cause performance issues with the game and/or tracker.

You'll just have to rely on the regular screen shot button, or you could try something like [OBS](https://obsproject.com/) to record your games as video so you can relive the awesomeness :smile:
